### ISSUE TITLE
Implementing new partner categorie donor?

### ISSUE THREAD

**Issue by benbrich** [OCA/donation#38]
When I understand things correctly, in the actual state of the modules, the donors are partner wise handled like customers.
Is there a reason why you did not implement a new partner "type/role/?" donor besides supplier and customer?
I think this would be more userfriendly considering eg. the displayed partners in donors view (Donations/Donations/Donors). Additionally most of the NGOs I know would not talk about the donors as their customers. Furthermore in Germany Non-Profits can to some degree offer services or other things, like commercial companies do. In this case they have donors on the one side and customers on the other and things could mix up. Thanks

**Comment by alexis-via** [comment]
I can understand the issue, which I would call a vocabulary issue. Of course, it is shocking to call a donor "a Customer". But, from the functional point of view, we don't really need this added "donor" boolean. What I want to avoid is the problem: I'm encoding a donation, I can't select the partner... as I don't find him, I'll create him... and I end up creating a double entry (because this partner already existed with customer=True and donor=False).

What we would need instead is to rename the "Customer" field as "Customer/Donor".
